spring:
  application:
    name: apigatewaykeycloak
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-service:8888}
  main:
    allow-bean-definition-overriding: true
