spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-service:8888}
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 5000
      maxAttempts: 20