spring:
  application:
    name: kafka-complains-producer
  kafka:
    producer:
      type-mappings: Complaint:ma.attijari.kafkacomplantsproducer.models.Complaint
      bootstrap-servers: kafka-1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: complaints
server:
  port: 8181