spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BK-beep/Complains-tracking-system-configuration.git
          default-label: master
          clone-on-start: true
          username: BK-beep
          password: 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
          force-pull: true
server:
  port: 8888
health:
  config:
    enabled: false